name: Build Equuleus
on: [push]
#  push:
#    branches:
#      - equuleus
jobs:
  CheckBuildRequired:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.existing_release_id.outputs.id != null }}
      commit: ${{ steps.check_commit.outputs.EQUULEUS_COMMIT }}
    steps:
      - name: Get vyos-build info
        id: check_commit
        run: |
          # Clone the build script
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build
          cd vyos-build
          COMMIT_ID=git rev-parse HEAD

          # Save the commit id as output
          echo '::set-output name=EQUULEUS_COMMIT::$COMMIT_ID'

          # Remove the cloned data
          cd ..
          rm -R vyos-build
      - name: Check local release exists
        id: existing_release_id
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ steps.check_commit.outputs.EQUULEUS_COMMIT }}
          doNotFailIfNotFound: true

  BuildAndRelease:
    needs: CheckBuildRequired
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
      - name: Pull docker image
        run: |
          docker pull "vyos/vyos-build:equuleus"
      - name: Prepare Build Script
        run: |
          mkdir ./.packer
          cat <<'EOF' >> ./.packer/build_script.sh
          #!/bin/bash
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build
          cd vyos-build
          git checkout {{ needs.CheckBuildRequired.outputs.commit }}

          # Configure
          ./configure --architecture amd64 --build-by "Github Actions" --build-type=release --version equuleus

          # Manipulate the image so that we add a default vyos-vyos user
          echo "This was the default config"
          cat ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default
          cp ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default.old
          cat ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default | sed -e 's#encrypted-password \$6\$QxPS.uk6mfo\$9QBSo8u1FkH16gMyAVhus6fU3LOzvLR9Z9.82m3tiHFAxTtIkhaZSWssSgzt4v4dGAL8rhVQxTg0oAG9/q11h/##' | sed -e 's/plaintext-password \"\"/plaintext-password \"vyos\"/' > ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default
          echo "This was the changed config"
          cat ./data/live-build-config/includes.chroot/opt/vyatta/etc/config.boot.default

          # Build the ISO and the GCE instance (ISO is required to build the GCE image)
          echo "$(pwd)"
          ls -l
          sudo make $1
          EOF
      - name: Build ISO
        run: |
          docker run \
              --rm \
              -v "$(pwd)":/vyos \
              -v "$(pwd)/.packer":/home/vyos_bld/.packer \
              -e VYOS_VERSION="equuleus" \
              -e BUILD_BY="Github Action" \
              -w /vyos \
              --privileged \
              --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
              -e GOSU_UID=$(id -u) \
              -e GOSU_GID=$(id -g) \
              "vyos/vyos-build:equuleus" \
              bash "/home/vyos_bld/.packer/build_script.sh" iso
      - uses: actions/upload-artifact@v3
        with:
          name: ISO
          path: |
            ./vyos-build/build/*.iso
      - name: Move ISO
        run: |
          mv ./vyos-build/build/*.iso ./
      - id: buildgce
        name: Build GCE Image
        run: |
          docker run \
              --rm \
              -v "$(pwd)":/vyos \
              -v "$(pwd)/.packer":/home/vyos_bld/.packer \
              -e VYOS_VERSION="equuleus" \
              -e BUILD_BY="Github Action" \
              -w /vyos \
              --privileged \
              --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
              -e GOSU_UID=$(id -u) \
              -e GOSU_GID=$(id -g) \
              "vyos/vyos-build:equuleus" \
              bash "/home/vyos_bld/.packer/build_script.sh" GCE
      - uses: actions/upload-artifact@v3
        with:
          name: GCE-IMGE
          path: ./vyos-build/build/*.tar.gz
      - name: Move GCE image
        run: |
          mv ./vyos-build/build/*.tar.gz ./
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ needs.CheckBuildRequired.outputs.commit }}"
          prerelease: true
          title: "Development Build"
          files: |
            *.iso
            *.tar.gz